config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'
 
 
  resources :contacts, except: [:new]
  resources :movies
 
  get 'welcome/index'
  get 'welcome/about'
  get 'about' => 'welcome#about', as: :about
  get 'contact' => 'contacts#new', as: :contact_me
  get 'thank_you' => 'contacts#thankYou', as: :thank_you

    resources :articles do
      resources :comments
    end  

    resources :tasks, except: [:show]

  
end

app/models/task.rb
class Task < ActiveRecord::Base
	
	module Status
		NOT_STARTED = 0
		STARTED = 1
		FINISHED = 2
	end

# scopes for prewritten queries
	scope :not_started, -> {where(status: Status::NOT_STARTED)}
	scope :started, -> {where(status: Status::STARTED)}
	scope :finished, -> {where(status: Status::FINISHED)}

# validate title
	validates :title, presence: true

# define status of input from user on views/tasks/index
	def not_started?
		self.status == Status::NOT_STARTED
	end

	def started?
		self.status == Status::STARTED
	end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  	# @tasks = Task.all
  	@finished_tasks = Task.finished
  	@unstarted_tasks = Task.not_started
    @started_tasks = Task.started

    @task = Task.all

  end

  def new
  	 @tasks = Task.new

  end

  def create
    @tasks = Task.new(task_params)
    # debugger
    respond_to do |format|
      if @tasks.save
        flash[:success] = "Your new task has been created."
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :index, status: :created, location: @tasks }
      else
        flash.now[:error] = "Your task was not created."
        format.html { render :new }
        format.json { render json: @tasks.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  	 @task = Task.find(params[:id])
	   @task.update_attribute(:status, params[:status].to_i)	 
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end


  private
	  def task_params
	    params.require(:task).permit(:title, :description)
	  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.html.erb
<% if task.not_started? %>
 	<li id="<%= dom_id(task) %>" class="list-group-item clearfix"><%= task.title %> 
 		<div class="finish-pause-btns pull-right">
	 		<span class="start-btn"> <%= link_to "Start", task_path(task, status: Task::Status::STARTED), method: :patch, remote: true, class: "btn btn-primary btn-xs" %>
	 		</span> 
	 		<span class="pull-right"> <%= link_to "Destroy", task_path(task), method: :delete, remote: true, class: "btn btn-danger btn-xs" %>
		 	</span>
		</div>

 	</li>
<% elsif task.started? %>
	<li id="<%= dom_id(task) %>" class="list-group-item clearfix"><%= task.title %>
		<div class="finish-pause-btns pull-right">
			<span class="pull-right Finish"> <%= link_to "Finish", task_path(task, status: Task::Status::FINISHED), method: :patch, remote: true, class: "btn btn-primary btn-xs" %>
	 		</span> 
	 		<span class="pause-btn"> <%= link_to "Pause", task_path(task, status: Task::Status::NOT_STARTED), method: :patch, remote: true, class: "btn btn-warning btn-xs" %> 
	 		</span>  
 	</div>
 		
 	</li>
<% else %>
	<li id="<%= dom_id(task) %>" class="list-group-item clearfix"><%= task.title %>
		<div class="finish-pause-btns pull-right">
	 		<span class="reset-btn"> <%= link_to "Reset", task_path(task,status: Task::Status::NOT_STARTED), method: :patch, remote: true, class: "btn btn-warning btn-xs" %>
	 		</span>
	 		<span class="pull-right"> <%= link_to "Destroy", task_path(task), method: :delete, remote: true, class: "btn btn-danger btn-xs" %>
	 		</span>
	 	</div>

 	</li>

<% end %>

app/views/tasks/_tasks.html.erb
<% if task.not_started? %>
 	<li class="list-group-item"><%= task.title %> - <%= task.description %> -
 		<span class="pull-right"> <%= link_to "Start", task_path(task), status: Task::Status::STARTED method: :patch, class: "btn btn-primary btn-xs" %> </span>  
 	</li>
<% elsif task.started? %>
	<li class="list-group-item"><%= task.title %> - <%= task.description %> -
 		<span class="pull-right"> <%= link_to "Stop", task_path(task), status: Task::Status::NOT_STARTED method: :patch, class: "btn btn-alert btn-xs" %> </span>  
 		 <span class="pull-right"> <%= link_to "Finish", task_path(task), status: Task::Status::FINISH method: :patch, class: "btn btn-primary btn-xs" %>
 		 </span>
 	</li>
<% else %>
	<li class="list-group-item"><%= task.title %> - <%= task.description %> -
 		<span class="pull-right"> <%= link_to "Reset", task_path(task), status: Task::Status::NOT_STARTED method: :patch, class: "btn btn-warning btn-xs" %>
 		</span>
 		<span class="pull-right"> <%= link_to "Finish", task_path(task), status: Task::Status::FINISH method: :patch, class: "btn btn-primary btn-xs" %>
 		</span> 
 	</li>

<% end %>

app/views/tasks/delete.js.erb
console.log("<%= dom_id(@task) %>")
$('#<%= dom_id(@task) %>').remove();

app/views/tasks/destroy.js.erb
console.log("<%= dom_id(@task) %>")
$('#<%= dom_id(@task) %>').remove();

app/views/tasks/index.html.erb
<div class="col-xs-12">
	<!-- Header -->
	<h1 class="tasks-header">Tasks</h1>

	<!-- Add new task button -->
	<div class="new-task-btn pull-right"><%= link_to 'Add Task', new_task_path, class: "btn btn-xs btn-success" %>
	</div>
	
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">  
    <li role="presentation" class="active"><a href="#current" aria-controls="current" role="tab" data-toggle="tab">Current Tasks</a></li>
    <li role="presentation" ><a href="#pending" aria-controls="pending" role="tab" data-toggle="tab">Pending Tasks</a></li>
    <li role="presentation"><a href="#completed" aria-controls="completed" role="tab" data-toggle="tab">Completed Tasks</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
   
	<div role="tabpanel" class="tab-pane active" id="current">
    	<ul id="tasks-<%= Task::Status::STARTED %>" class="list-group">
		<%= render @started_tasks %>
		</ul>
    </div>
    
    <div role="tabpanel" class="tab-pane" id="pending">
    	<ul id="tasks-<%= Task::Status::NOT_STARTED %>" class="list-group">
		<%= render @unstarted_tasks %>
		</ul>
    </div>

    <div role="tabpanel" class="tab-pane" id="completed">	
    	<ul id="tasks-<%= Task::Status::FINISHED %>" class="list-group">
		<%= render @finished_tasks %>
		</ul>
    </div>
  </div>
</div>













	

app/views/tasks/new.html.erb
<div class="col-xs-12">
  <h1>Create a new task</h1>
  <%= form_for(@tasks) do |f| %>
    <% if @tasks.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tasks.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
        <% @tasks.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>


    <div class="actions">
      <input class="btn btn-success" type="submit" name="commit" value="Create Task">
   </div>

  <% end %>
</div>

app/views/tasks/update.html.erb
update.html.erb

app/views/tasks/update.js.erb
console.log("<%= dom_id(@task) %>")
$('#<%= dom_id(@task) %>').remove();
$('ul#tasks-<%= @task.status %>').append('<%= j render(@task) %>');