config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'
 
 
  resources :contacts, except: [:new]
  resources :movies
 
  get 'welcome/index'
  get 'welcome/about'
  get 'about' => 'welcome#about', as: :about
  get 'contact' => 'contacts#new', as: :contact_me
  get 'thank_you' => 'contacts#thankYou', as: :thank_you

    resources :articles do
      resources :comments
    end  

    resources :tasks, except: [:show]

  
end

app/views/common/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error" ) %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/common/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Blog Site", root_path, class: "navbar-brand" %>
          
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
             <li><%= link_to "Movies", movies_path %></li>
			 <li><%= link_to "Todo", tasks_path %></li>
			 <li><%= link_to "Blog", articles_path %></li>
			 <li><%= link_to "About", about_path %></li>
			 <li><%= link_to "Contact Me", contact_me_path %></li>



      <% if user_signed_in? %>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Menu <span class="caret"></span></a>
              <ul class="dropdown-menu">
               
                <li role="separator" class="divider"></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              </ul>
          </li>
        <% else %> 
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
          </ul>
        </div><!-- /.nav-collapse -->

        
          
          
        <% else %>



       </ul>

        


      </div><!-- /.container -->
    </nav>

app/views/common/header.html.erb
<nav>
 <%= link_to "Home", root_path %>
 <%= link_to "Blog", articles_path %>
 <%= link_to "FAQs", faq_path %>
 <%= link_to "Contact Us", contact_path %>
</nav>